apiVersion: apps/v1
kind: Deployment
metadata:
  name: ors-app
spec:
  replicas: 3
  template:
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      containers:
        - name: ors-app
          readinessProbe:
            httpGet:
              path: "/ors/health"
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 5
            failureThreshold: 3
